name: Node.js CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19' 

    #install dependencies and run tests
    - name: Install dependencies and run tests
      run: |
        npm install
        npm test

    # deployment hook 
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2     #tricky spelling (distributhor)
      env: 
        webhook_url: ${{secrets.DEPLOY_HOOK_URL}}
        webhook_secret: ${{secrets.DEPLOY_HOOK_KEY}}

    # deploy using render
    - name: Deploy to Render
      uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY}}
        service-id: "srv-cj8gn9sl975s73b1adp0"
        retries: 20
        wait: 16000
        sleep: 30000


        
